<? 
/**
 * This is the classesLinks partail
 * 
 * @author	   Florian Schuhmann
 * @package    Default
 * @subpackage viewScripts
 */
?>
<a href="<?= $this->url(array(
            		'controller' => 'entry',
            	    'action' => 'index',
            	    'class_id' =>$this->class->class_id),null,true) ?>">
<?php

echo ($this->class->classType == 'Group')? $this->class->parent->title . '(':'';
echo  $this->class->title;
echo ($this->class->classType == 'Group')? ')' : '';
?></a>