<div class="comments">
    <div class="commentsHead">
	    <div class="commentsId">#<?=$this->escape($this->comment->getId())?></div>
    	<div class="commentsOwner"><?=$this->escape($this->comment->getUser())?></div>
    	<div class="commentsDate"><?=$this->escape($this->comment->getCrdate())?></div>
    	<div class="clear"></div>
    </div>
    <div class="commentsContent"><?=$this->escape($this->comment->getComment())?></div>
    <div class="commentsFunctions"><?=$this->deleteCommentLink($this->comment->getUser(), $this->comment->getId())?></div>
</div>
