<?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>SPIRIT = (ServicePoint: Information) => Read IT</title>
  <?=$this->headLink()?>
  <?=$this->headMeta()?>
  <?=$this->jQuery()?>
  <?=$this->headScript()?>
</head>
<body>
<header id="header">
<div id="logo"></div>
<div id="pot"></div>
<div id="clips"></div>
<div class="clear"></div>
</header>
<div id="container"><nav>
	<?=$this->navigation()->menu()->setMaxDepth(0)?> <!-- This line will output the navigation -->
</nav>
<div id="doc">
	<?=$this->navigation()->menu()->renderMenu(null, array(
    'minDepth' => 1,
    'maxDepth' => 1,
    'onlyActiveBranch' => true,
    'renderParents' => false,
	'ulClass' => 'subnav'))?> <!-- This line will output the navigation -->
<section id="content">
	<?= $this->layout()->content?> <!-- This line will output the content -->
</section> 
<aside class="sidebar">
<h2>Sidebar</h2>
<p>Lorum ipsum...</p>
</aside> <footer> <a href="#">Impressum</a> </footer></div>
<div class="clear"></div>
</div>

</body>
</html>
