DROP TABLE IF EXISTS entry,users,comment;

CREATE TABLE entry (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user VARCHAR(255) NOT NULL,
  displayName VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  news TEXT NULL,
  crdate VARCHAR(10) NOT NULL,
  semester VARCHAR(255) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users (
  id INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(32) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE comment (
  id INTEGER NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  entryId INTEGER NOT NULL,
  user VARCHAR(255) NOT NULL,
  comment TEXT NULL,
  crdate VARCHAR(10) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;