CREATE TABLE entry (
  id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
  user VARCHAR(255) NOT NULL,
  displayName VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  news TEXT NULL,
  crdate DATETIME NOT NULL,
  semester VARCHAR(255) NULL
);

CREATE TABLE users (
  id INTEGER  NOT NULL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(32) NULL
);

CREATE TABLE comment (
  id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
  entryId INTEGER NOT NULL,
  user VARCHAR(255) NOT NULL,
  comment TEXT NULL,
  crdate VARCHAR(10) NOT NULL
);