CREATE TABLE entry (
  id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
  cruser VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  text TEXT NULL,
  crdate DATETIME NOT NULL
);


CREATE TABLE users (
  id INTEGER  NOT NULL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(32) NULL,
);

CREATE TABLE comment (
  id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
  entryId INTEGER NOT NULL,
  cruser VARCHAR(255) NOT NULL,
  text TEXT NULL,
  crdate DATETIME NOT NULL
);